import type { Audit, Lead, Client } from "@repo/db";
import { leadBusinessName } from "../leads-helpers";

// F9: escape order — backslash FIRST, then markdown control chars (incl.
// backtick), then HTML-sensitive chars. Order is load-bearing: escaping
// backslash after other chars would double-escape the inserted backslashes.
const HTML_ENTITIES: Record<string, string> = {
  "<": "&lt;",
  ">": "&gt;",
  "&": "&amp;",
};

export function escapeMarkdownText(s: string | null | undefined): string {
  if (s == null) return "";
  return s
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/[*_#\[\]()]/g, (c) => "\\" + c)
    .replace(/[<>&]/g, (c) => HTML_ENTITIES[c]!);
}

export type AuditExportSubject =
  | { kind: "lead"; lead: Lead }
  | { kind: "client"; client: Client }
  | { kind: "orphan" };

function subjectHeader(subject: AuditExportSubject): {
  businessName: string;
  contactName: string;
  email: string;
  phone: string;
  kindLabel: string;
} {
  if (subject.kind === "lead") {
    return {
      businessName: escapeMarkdownText(leadBusinessName(subject.lead)),
      contactName: escapeMarkdownText(subject.lead.name),
      email: escapeMarkdownText(subject.lead.email),
      phone: escapeMarkdownText(subject.lead.phone ?? ""),
      kindLabel: "Lead",
    };
  }
  if (subject.kind === "client") {
    return {
      businessName: escapeMarkdownText(subject.client.businessName),
      contactName: escapeMarkdownText(subject.client.contactName),
      email: escapeMarkdownText(subject.client.email ?? ""),
      phone: escapeMarkdownText(subject.client.phone ?? ""),
      kindLabel: "Client",
    };
  }
  return {
    businessName: "(unattached)",
    contactName: "(unattached)",
    email: "",
    phone: "",
    kindLabel: "Orphan",
  };
}

function section(title: string, body: string | null | undefined): string {
  const value = (body ?? "").trim();
  if (!value) return `## ${title}\n\n_None recorded._\n`;
  return `## ${title}\n\n${escapeMarkdownText(value)}\n`;
}

export function renderAuditMarkdown(
  audit: Audit,
  subject: AuditExportSubject,
  generatedAt: Date = new Date(),
): string {
  const head = subjectHeader(subject);
  const dateIso = audit.createdAt.toISOString().slice(0, 10);
  const generatedIso = generatedAt.toISOString();

  const contact = [head.email, head.phone].filter(Boolean).join(" · ");
  const contactLine = contact ? ` (${contact})` : "";

  return [
    `# System Audit — ${head.businessName}`,
    "",
    `**Date:** ${dateIso}`,
    `**${head.kindLabel}:** ${head.contactName}${contactLine}`,
    "",
    section("Business overview", audit.businessOverview),
    section("Current tools", audit.currentTools),
    section("Pain points", audit.painPoints),
    section("Opportunities", audit.opportunities),
    section("Recommended systems", audit.recommendedSystems),
    section("Next steps", audit.nextSteps),
    "---",
    "",
    `_Generated by Conscience Os Internal Ops — ${generatedIso}_`,
    "",
  ].join("\n");
}
